### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Fale** [rfinnie/2ping#4]
I hope to see soon the python3 support since many distributions are shifting to python3 very soon. Python 2.7 will be supported until 2020, but I think 2ping should start working toward python3 soon to arrive without any problem to that date

**Comment by rfinnie** [comment]
2ping 4.0 has been released, and has been rewritten for Python 3.  I've updated the sample 2ping.spec, but in general it should be a simple matter of 2 to 3 for Rawhide.
