### ISSUE TITLE
Error on non encrypted session

### ISSUE THREAD

**Issue by joe1981alAPR** [rfinnie/2ping#5]
When running 2 ping I receive a NoneType error after 10-15 seconds.

If I comment out lines 1048 - 1051 in cli.py then this does not happen.

I believe this is because I am not running an encrypted session, but it is trying to cleanup something that doesn't exist.  Maybe wrap this in an if to check if sock_class.encrypted_sessions.keys() actual has data.

**Comment by rfinnie** [comment]
Fixed, thank you!
