### ISSUE TITLE
Non executable scripts in site-packages

### ISSUE THREAD

**Issue by kbabioch** [rfinnie/2ping#6]
There are a couple of scripts that are not executable, but still have the shebang line on top:

    non-executable-script /usr/lib/python3.6/site-packages/twoping/best_poller.py 644 /usr/bin/env python3
    non-executable-script /usr/lib/python3.6/site-packages/twoping/cli.py 644 /usr/bin/env python3
    non-executable-script /usr/lib/python3.6/site-packages/twoping/crc32.py 644 /usr/bin/env python3
    non-executable-script /usr/lib/python3.6/site-packages/twoping/monotonic_clock.py 644 /usr/bin/env python3

Most probably you want to remove this line ;). These are warnings from our build service (OBS), it would be nice if this could be fixed in an upcoming version.

**Comment by rfinnie** [comment]
Fixed with 2ping 4.4 (all Python module files made non-executable and shebangs removed), thanks!
